[tools]
1password = "latest"
bat = "latest"
bun = "latest"
colima = "latest"
fzf = "latest"
gcloud = "latest"
github-cli = "latest"
jq = "latest"
lazygit = "latest"
lima = "latest"
node = "latest"
"npm:@google/gemini-cli" = "latest"
opencode = "latest"
rg = "latest"
starship = "latest"
